Schema.InvMassTbl = {}
Schema.Icons = {}
Schema.InvNameTbl = {}
------------------------
--IMAGE OF ITEMS

--WEPS
Schema.Icons[".44 Magnum Revolver"] = "pw_fallout/icons/weapons/44magnum.png"
Schema.Icons["10mm Carbine"] = "pw_fallout/icons/weapons/10mm_sub.png"
Schema.Icons["9 Iron"] = "pw_fallout/icons/weapons/9iron.png"
Schema.Icons["9mm Pistol"] = "pw_fallout/icons/weapons/9mm_pistol.png"
Schema.Icons["9mm Sub-Machine Gun"] = "pw_fallout/icons/weapons/9mm_sub.png"
Schema.Icons["AK-112"] = "pw_fallout/icons/weapons/ak112.png"
Schema.Icons["10mm Sub-Machine Gun"] = "pw_fallout/icons/weapons/10mm_sub.png"
Schema.Icons["10mm Pistol"] = "pw_fallout/icons/weapons/10mm_pistol.png"
Schema.Icons["Baseball Bat"] = "pw_fallout/icons/weapons/baseballbat.png"
Schema.Icons["Police Baton"] = "pw_fallout/icons/weapons/baton.png"
Schema.Icons["Bottlecap Mine"] = "pw_fallout/icons/weapons/botcap.png"
Schema.Icons["Bumper Sword"] = "pw_fallout/icons/weapons/bumper.png"
Schema.Icons["Chinese Assault Rifle"] = "pw_fallout/icons/weapons/chinese_ar.png"
Schema.Icons["Alien Blaster"] = "pw_fallout/icons/weapons/blaster.png"
Schema.Icons["Combat Shotgun"] = "pw_fallout/icons/weapons/combatsg.png"
Schema.Icons["Cowboy Repeater"] = "pw_fallout/icons/weapons/cowboyr.png"
Schema.Icons["Double Barreled Shotgun"] = "pw_fallout/icons/weapons/doublebar.png"
Schema.Icons["Fatman"] = "pw_fallout/icons/weapons/fatman.png"
Schema.Icons["Frag Grenade"] = "pw_fallout/icons/weapons/frag_grenade.png"
Schema.Icons["Frag Mine"] = "pw_fallout/icons/weapons/frag_mine.png"
Schema.Icons["Gatling Laser"] = "pw_fallout/icons/weapons/gattlinglaser.png"
Schema.Icons["Hunting Rifle"] = "pw_fallout/icons/weapons/hunting_rifle.png"
Schema.Icons["Kicthen Knife"] = "pw_fallout/icons/weapons/knife.png"
Schema.Icons["Laser Pistol"] = "pw_fallout/icons/weapons/laser_pistol.png"
Schema.Icons["Laser Rifle"] = "pw_fallout/icons/weapons/laser_rifle.png"
Schema.Icons["Machete"] = "pw_fallout/icons/weapons/machete.png"
Schema.Icons["Multiplas Rifle"] = "pw_fallout/icons/weapons/multiplas.png"
Schema.Icons["Nephi's Golf Driver"] = "pw_fallout/icons/weapons/9iron.png"
Schema.Icons["Pickaxe"] = "pw_fallout/icons/weapons/pipe.png"
Schema.Icons["Plasma Pistol"] = "pw_fallout/icons/weapons/plasmapistol.png"
Schema.Icons["Plasma Rifle"] = "pw_fallout/icons/weapons/plasmarifle.png"
Schema.Icons["Sawn-off Shotgun"] = "pw_fallout/icons/weapons/sawnoff.png"
Schema.Icons["Service Rifle"] = "pw_fallout/icons/weapons/service.png"
Schema.Icons["Shishkebab"] = "pw_fallout/icons/weapons/shish.png"
Schema.Icons["Silenced 10mm Pistol"] = "pw_fallout/icons/weapons/sil10mm.png"
Schema.Icons["Sniper Rifle"] = "pw_fallout/icons/weapons/sniper.png"
Schema.Icons["Super Sledge Hammer"] = "pw_fallout/icons/weapons/supersledge.png"
Schema.Icons["Tesla-Beaton Prototype"] = "pw_fallout/icons/weapons/teslab.png"
Schema.Icons["Turbo Plasma Rifle"] = "pw_fallout/icons/weapons/plasmarifle.png"
--Outfits
Schema.Icons["Leather Armor"] = "pw_fallout/icons/apparel/leatherarmor.png"
Schema.Icons["Vault Security Uniform"] = "pw_fallout/icons/apparel/vaultsec.png"
Schema.Icons["Vault Security Helmet"] = "pw_fallout/icons/apparel/vaultsec_helm.png"
Schema.Icons["Dead Horse Tribal"] = "pw_fallout/icons/apparel/deadhorse.png"
Schema.Icons["Hazmat Helmet"] = "pw_fallout/icons/apparel/hazmat_helm.png"
Schema.Icons["Engineer Jumpsuit"] = "pw_fallout/icons/apparel/jumpsuit.png"
Schema.Icons["Lab Coat"] = "pw_fallout/icons/apparel/labcoat.png"
Schema.Icons["Miner Armor"] = "pw_fallout/icons/apparel/miner.png"
Schema.Icons["Miner Helmet"] = "pw_fallout/icons/apparel/miner_helm.png"
Schema.Icons["Party Hat"] = "pw_fallout/icons/apparel/partyhat.png"
Schema.Icons["Bandana"] = "pw_fallout/icons/apparel/bandana.png"
Schema.Icons["Radiation Suit"] = "pw_fallout/icons/apparel/radsuit.png"
Schema.Icons["Vault Suit"] = "pw_fallout/icons/apparel/vault101.png"
Schema.Icons["Merc Charmer Outfit"] = "pw_fallout/icons/apparel/slaver1.png"
Schema.Icons["Merc Troublemaker Outfit"] = "pw_fallout/icons/apparel/slaver2.png"
Schema.Icons["Merc Adventurer Outfit"] = "pw_fallout/icons/apparel/slaver3.png"
Schema.Icons["Merc Veteren Outfit"] = "pw_fallout/icons/apparel/slaver4.png"
Schema.Icons["Wasteland Doctor Outfit"] = "pw_fallout/icons/apparel/doc.png"
Schema.Icons["Merchant Outfit"] = "pw_fallout/icons/apparel/merchant.png"
Schema.Icons["Brahmin-skin Outfit"] = "pw_fallout/icons/apparel/waste_overall.png"
Schema.Icons["Wasteland Settler Outfit"] = "pw_fallout/icons/apparel/waste_rags.png"
Schema.Icons["Wasteland Wanderer Outfit"] = "pw_fallout/icons/apparel/native.png"

Schema.Icons["Raider Blastmaster Armor"] = "pw_fallout/icons/apparel/raider1.png"
Schema.Icons["Raider Sadist Armor"] = "pw_fallout/icons/apparel/raider3.png"
Schema.Icons["Raider Badlands Armor"] = "pw_fallout/icons/apparel/raider2.png"
Schema.Icons["Raider Painspike Armor"] = "pw_fallout/icons/apparel/blastmaster.png"
Schema.Icons["Welding Mask"] = "pw_fallout/icons/apparel/welding_mask.png"
Schema.Icons["Raider Badlands Mask"] = "pw_fallout/icons/apparel/badlands_mask.png"
Schema.Icons["Raider Sadist Mask"] = "pw_fallout/icons/apparel/sadist_mask.png"
Schema.Icons["Hockey Mask"] = "pw_fallout/icons/apparel/hockey_mask.png"

Schema.Icons["Chinese Commando Uniform"] = "pw_fallout/icons/apparel/chinesecom.png"
Schema.Icons["Powder Ganger Uniform"] = "pw_fallout/icons/apparel/powdergang.png"
Schema.Icons["Liberty Party Uniform"] = "pw_fallout/icons/apparel/powdergang.png"
Schema.Icons["Liberty Party Hat"] = "pw_fallout/icons/apparel/libhat.png"

Schema.Icons["Chinese Stealth Suit"] = "pw_fallout/icons/apparel/chinesestealth.png"
Schema.Icons["Chinese Stealth Helmet"] = "pw_fallout/icons/apparel/chinesestealth.png"
Schema.Icons["Combat Armor"] = "pw_fallout/icons/apparel/combatarmor.png"
Schema.Icons["Combat Helmet"] = "pw_fallout/icons/apparel/combat_helm.png"
Schema.Icons["Formal Suit"] = "pw_fallout/icons/apparel/formalsuit.png"
Schema.Icons["Mysterious Suit"] = "pw_fallout/icons/apparel/casual_suit.png"
Schema.Icons["Mark I Combat Armor"] = "pw_fallout/icons/apparel/combatarmor.png"
Schema.Icons["Mark I Combat Helmet"] = "pw_fallout/icons/apparel/combat_helm.png"
Schema.Icons["Mark II Combat Armor"] = "pw_fallout/icons/apparel/combatarmor.png"
Schema.Icons["Mark II Combat Helmet"] = "pw_fallout/icons/apparel/combat_helm.png"

Schema.Icons["Mark II Leather Armor"] = "pw_fallout/icons/apparel/leatherarmor_m2.png"
Schema.Icons["Metal Armor"] = "pw_fallout/icons/apparel/metalarmor.png"
Schema.Icons["Metal Helmet"] = "pw_fallout/icons/apparel/metal_helm.png"

Schema.Icons["Slave Rags"] = "pw_fallout/icons/apparel/slaverags.png"
Schema.Icons["Legion Veteren"] = "pw_fallout/icons/apparel/legion_vet.png"
Schema.Icons["Caesars Outfit"] = "pw_fallout/icons/apparel/caesar.png"
Schema.Icons["Legion Recruit"] = "pw_fallout/icons/apparel/legion_recruit.png"
Schema.Icons["Legion Prime"] = "pw_fallout/icons/apparel/legion_prime.png"
Schema.Icons["Legion Explorer"] = "pw_fallout/icons/apparel/legion_prime.png"
Schema.Icons["Legion Vexillarius"] = "pw_fallout/icons/apparel/legion_vex.png"
Schema.Icons["Legion Pretorian"] = "pw_fallout/icons/apparel/legion_pre.png"

Schema.Icons["Legion Veteren Bandana"] = "pw_fallout/icons/apparel/legion_decanus.png"
Schema.Icons["Legion Prime Bandana"] = "pw_fallout/icons/apparel/legion_decanus.png"
Schema.Icons["Legion Explorer Bandana"] = "pw_fallout/icons/apparel/legion_decanus.png"
Schema.Icons["Legion Recruit Helmet"] = "pw_fallout/icons/apparel/legion_recruit_helm.png"
Schema.Icons["Legion Prime Helmet"] = "pw_fallout/icons/apparel/legion_prime_helm.png"
Schema.Icons["Legion Hood"] = "pw_fallout/icons/apparel/legion_hood.png"
Schema.Icons["Legion Vexillarius Hood"] = "pw_fallout/icons/apparel/legion_vex_helm.png"

Schema.Icons["Centurion Armor"] = "pw_fallout/icons/apparel/legion_cent.png"
Schema.Icons["Centurion Helmet"] = "pw_fallout/icons/apparel/legion_cent_helm.png"

Schema.Icons["T-45d Power Armor"] = "pw_fallout/icons/apparel/power.png"
Schema.Icons["T-51b Power Armor"] = "pw_fallout/icons/apparel/power.png"
Schema.Icons["T-45d Power Helmet"] = "pw_fallout/icons/apparel/power_h.png"
Schema.Icons["T-51b Power Helmet"] = "pw_fallout/icons/apparel/power_h.png"
Schema.Icons["Brotherhood Scribe Robes"] = "pw_fallout/icons/apparel/scribe.png"
Schema.Icons["Recon Armor"] = "pw_fallout/icons/apparel/reconarmor.png"

Schema.Icons["NCR Trooper Outfit"] = "pw_fallout/icons/apparel/ncr_troop.png"
Schema.Icons["NCR Mantle Outfit"] = "pw_fallout/icons/apparel/ncr_mantle.png"
Schema.Icons["NCR Bandoleer Outfit"] = "pw_fallout/icons/apparel/ncr_band.png"
Schema.Icons["NCR Face Wrap Outfit"] = "pw_fallout/icons/apparel/ncr_face.png"
Schema.Icons["Trooper Helmet"] = "pw_fallout/icons/apparel/ncr_helm.png"
Schema.Icons["Red Beret"] = "pw_fallout/icons/apparel/ncr_beret.png"
Schema.Icons["Green Beret"] = "pw_fallout/icons/apparel/ncr_beret.png"
Schema.Icons["Cowboy Hat"] = "pw_fallout/icons/apparel/cowboy_hat.png"
Schema.Icons["Pre-War Business Hat"] = "pw_fallout/icons/apparel/cowboy_hat.png"
Schema.Icons["Dark Business Hat"] = "pw_fallout/icons/apparel/tophat.png"
Schema.Icons["Old Cowboy Hat"] = "pw_fallout/icons/apparel/cowboy_hat.png"
Schema.Icons["Combat Ranger Armor"] = "pw_fallout/icons/apparel/ncr_combr.png"
Schema.Icons["Combat Ranger Helmet"] = "pw_fallout/icons/apparel/ncr_combr_helm.png"
Schema.Icons["Patrol Ranger Armor"] = "pw_fallout/icons/apparel/ncr_armor.png"

Schema.Icons["Enclave Power Armor"] = "pw_fallout/icons/apparel/enclave_armor.png"
Schema.Icons["Enclave Power Helmet"] = "pw_fallout/icons/apparel/enclave_helm.png"
Schema.Icons["Enclave Hellfire Armor"] = "pw_fallout/icons/apparel/enclave_helf.png"
Schema.Icons["Enclave Hellfire Helmet"] = "pw_fallout/icons/apparel/enclave_helf_helm.png"
Schema.Icons["Remenants Power Armor"] = "pw_fallout/icons/apparel/enclave_adv.png"
Schema.Icons["Remenants Power Helmet"] = "pw_fallout/icons/apparel/enclave_adv_helm.png"
--AID
Schema.Icons["Stimpack"] = "pw_fallout/icons/aid/stim.png"
Schema.Icons["Doctors Bag"] = "pw_fallout/icons/aid/docbag.png"
Schema.Icons["Stealth Boy"] = "pw_fallout/icons/aid/stealthboy.png"
Schema.Icons["Buffout"] = "pw_fallout/icons/aid/buffout.png"
Schema.Icons["Healing Powder"] = "pw_fallout/icons/aid/gland.png"
Schema.Icons["Jet"] = "pw_fallout/icons/aid/jet.png"
Schema.Icons["MedX"] = "pw_fallout/icons/aid/medx.png"
Schema.Icons["Psycho"] = "pw_fallout/icons/aid/psycho.png"
Schema.Icons["Super Stimpack"] = "pw_fallout/icons/aid/superstim.png"
Schema.Icons["Ant Meat"] = "pw_fallout/icons/aid/antmeat.png"
Schema.Icons["Atomic Cocktail"] = "pw_fallout/icons/aid/atomic_cock.png"
Schema.Icons["Cram"] = "pw_fallout/icons/aid/cram.png"
Schema.Icons["Iguana Bits"] = "pw_fallout/icons/aid/ig_bits.png"
Schema.Icons["Iguana Stew"] = "pw_fallout/icons/aid/stew.png"
Schema.Icons["Iguana on a Stick"] = "pw_fallout/icons/aid/ig_stick.png"
Schema.Icons["InstaMash"] = "pw_fallout/icons/aid/mash.png"
Schema.Icons["Molerat Steak"] = "pw_fallout/icons/aid/steak.png"
Schema.Icons["Molerat Meat"] = "pw_fallout/icons/aid/dog_meat.png"
Schema.Icons["Nuka Cola"] = "pw_fallout/icons/aid/nuka.png"
Schema.Icons["Pork N Beans"] = "pw_fallout/icons/aid/porkbeans.png"
Schema.Icons["Strange Meat"] = "pw_fallout/icons/aid/steak.png"
Schema.Icons["Strange Stew"] = "pw_fallout/icons/aid/stew.png"
--MISC
Schema.Icons["10mm Casing"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Belt"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Bloodpack"] = "pw_fallout/icons/misc/bloodpack.png"
Schema.Icons["Brahmin Dung"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Cherry Bomb"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Deathclaw Egg"] = "pw_fallout/icons/misc/death_egg.png"
Schema.Icons["Deathclaw Hand"] = "pw_fallout/icons/misc/death_hand.png"
Schema.Icons["E-Cell Casing"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Gecko Hide"] = "pw_fallout/icons/misc/gecko_hide.png"
Schema.Icons["Glass"] = "pw_fallout/icons/misc/container.png"
Schema.Icons["Holo Disk"] = "pw_fallout/icons/misc/holotape.png"
Schema.Icons["Lead"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Leather"] = "pw_fallout/icons/misc/gecko_hide.png"
Schema.Icons["Liquid Coolant"] = "pw_fallout/icons/misc/liquid_coolant.png"
Schema.Icons["Lunchbox"] = "pw_fallout/icons/misc/lunchbox.png"
Schema.Icons["Scope"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Scrap Electronics"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Metal Fragments"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Scrap Metal"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Sensor Module"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Soda Bottle"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Steam Gauge"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Surgical Tubing"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Syringe"] = "pw_fallout/icons/misc/junk.png"
Schema.Icons["Turpentine"] = "pw_fallout/icons/misc/junk.png"
--AMMO
Schema.Icons[".308 Rounds"] = "pw_fallout/icons/ammo/308.png"
Schema.Icons[".44 Magnum Rounds"] = "pw_fallout/icons/ammo/44.png"
Schema.Icons[".10mm Rounds"] = "pw_fallout/icons/ammo/10mm.png"
Schema.Icons["12 Gauge Rounds"] = "pw_fallout/icons/ammo/12g.png"
Schema.Icons["5.56mm Rounds"] = "pw_fallout/icons/ammo/556.png"
Schema.Icons["5mm Rounds"] = "pw_fallout/icons/ammo/556.png"
Schema.Icons["9mm Rounds"] = "pw_fallout/icons/ammo/9mm.png"
Schema.Icons["Alien Power Cell"] = "pw_fallout/icons/ammo/apcell.png"
Schema.Icons["EC-Pack"] = "pw_fallout/icons/ammo/mfcell.png"
Schema.Icons["Energy-Cell"] = "pw_fallout/icons/ammo/e_cell.png"
Schema.Icons["Microfusion Cell"] = "pw_fallout/icons/ammo/mfcell.png"
Schema.Icons["Mini-Nuke"] = "pw_fallout/icons/ammo/nuke.png"

----------------------------------------------------------------------------
--WEIGHT OF ITEMS-------------------------------------------
----------------------------------------------------------------------------
Schema.InvMassTbl["holodisk"] = 0.1
Schema.InvMassTbl["metalfrag"] = 1
Schema.InvMassTbl["scrapmetal"] = 2
--APPAREL
Schema.InvMassTbl["T-51b Power Armor"] = 40
Schema.InvMassTbl["T-45d Power Armor"] = 45
Schema.InvMassTbl["Leather Armor"] = 15

Schema.InvMassTbl["Vault Security Uniform"] = 12
Schema.InvMassTbl["Vault Security Helmet"] = 3
Schema.InvMassTbl["Dead Horse Tribal"] = 1
Schema.InvMassTbl["Hazmat Helmet"] = 4
Schema.InvMassTbl["Engineer Jumpsuit"] = 2
Schema.InvMassTbl["Lab Coat"] = 2
Schema.InvMassTbl["Miner Armor"] = 20
Schema.InvMassTbl["Miner Helmet"] = 3
Schema.InvMassTbl["Party Hat"] = 1
Schema.InvMassTbl["Bandana"] = 1
Schema.InvMassTbl["Radiation Suit"] = 10
Schema.InvMassTbl["Vault Suit"] = 2
Schema.InvMassTbl["Merc Charmer Outfit"] = 11
Schema.InvMassTbl["Merc Troublemaker Outfit"] = 11
Schema.InvMassTbl["Merc Adventurer Outfit"] = 11
Schema.InvMassTbl["Merc Veteren Outfit"] = 11
Schema.InvMassTbl["Wasteland Doctor Outfit"] = 1
Schema.InvMassTbl["Merchant Outfit"] = 5
Schema.InvMassTbl["Brahmin-skin Outfit"] = 1
Schema.InvMassTbl["Wasteland Settler Outfit"] = 1
Schema.InvMassTbl["Wasteland Wanderer Outfit"] = 1

Schema.InvMassTbl["Raider Blastmaster Armor"] = 16
Schema.InvMassTbl["Raider Sadist Armor"] = 16
Schema.InvMassTbl["Raider Badlands Armor"] = 16
Schema.InvMassTbl["Raider Painspike Armor"] = 16
Schema.InvMassTbl["Welding Mask"] = 5
Schema.InvMassTbl["Raider Badlands Mask"] = 2
Schema.InvMassTbl["Raider Sadist Mask"] = 2
Schema.InvMassTbl["Hockey Mask"] = 2

Schema.InvMassTbl["Chinese Commando Uniform"] = 6
Schema.InvMassTbl["Powder Ganger Uniform"] = 15
Schema.InvMassTbl["Liberty Party Uniform"] = 15
Schema.InvMassTbl["Liberty Party Hat"] = 2

Schema.InvMassTbl["Chinese Stealth Suit"] = 8
Schema.InvMassTbl["Chinese Stealth Helmet"] = 2
Schema.InvMassTbl["Combat Armor"] = 25
Schema.InvMassTbl["Combat Helmet"] = 6
Schema.InvMassTbl["Formal Suit"] = 1
Schema.InvMassTbl["Mysterious Suit"] = 1
Schema.InvMassTbl["Mark I Combat Armor"] = 20
Schema.InvMassTbl["Mark I Combat Helmet"] = 3
Schema.InvMassTbl["Mark II Combat Armor"] = 15
Schema.InvMassTbl["Mark II Combat Helmet"] = 2

Schema.InvMassTbl["Mark II Leather Armor"] = 10
Schema.InvMassTbl["Metal Armor"] = 25
Schema.InvMassTbl["Metal Helmet"] = 8

Schema.InvMassTbl["Slave Rags"] = 1
Schema.InvMassTbl["Legion Veteren"] = 13
Schema.InvMassTbl["Caesars Outfit"] = 10
Schema.InvMassTbl["Legion Recruit"] = 15
Schema.InvMassTbl["Legion Prime"] = 13
Schema.InvMassTbl["Legion Explorer"] = 20
Schema.InvMassTbl["Legion Vexillarius"] = 15
Schema.InvMassTbl["Legion Pretorian"] = 20

Schema.InvMassTbl["Legion Veteren Bandana"] = 3
Schema.InvMassTbl["Legion Prime Bandana"] = 3
Schema.InvMassTbl["Legion Explorer Bandana"] = 3
Schema.InvMassTbl["Legion Recruit Helmet"] = 4
Schema.InvMassTbl["Legion Prime Helmet"] = 4
Schema.InvMassTbl["Legion Hood"] = 2
Schema.InvMassTbl["Legion Vexillarius Hood"] = 2

Schema.InvMassTbl["Centurion Armor"] = 35
Schema.InvMassTbl["Centurion Helmet"] = 10

Schema.InvMassTbl["Brotherhood Scribe Robes"] = 2
Schema.InvMassTbl["Recon Armor"] = 10

Schema.InvMassTbl["NCR Trooper Outfit"] = 15
Schema.InvMassTbl["NCR Mantle Outfit"] = 15
Schema.InvMassTbl["NCR Bandoleer Outfit"] = 16
Schema.InvMassTbl["NCR Face Wrap Outfit"] = 15
Schema.InvMassTbl["Trooper Helmet"] = 2
Schema.InvMassTbl["Red Beret"] = 1
Schema.InvMassTbl["Green Beret"] = 1
Schema.InvMassTbl["Cowboy Hat"] = 1
Schema.InvMassTbl["Pre-War Business Hat"] = 1
Schema.InvMassTbl["Dark Business Hat"] = 1
Schema.InvMassTbl["Old Cowboy Hat"] = 1
Schema.InvMassTbl["Combat Ranger Armor"] = 20
Schema.InvMassTbl["Combat Ranger Helmet"] = 5
Schema.InvMassTbl["Patrol Ranger Armor"] = 20

Schema.InvMassTbl["Enclave Power Armor"] = 35
Schema.InvMassTbl["Enclave Power Helmet"] = 10
Schema.InvMassTbl["Enclave Hellfire Armor"] = 30
Schema.InvMassTbl["Enclave Hellfire Helmet"] = 5
Schema.InvMassTbl["Remenants Power Armor"] = 40
Schema.InvMassTbl["Remenants Power Helmet"] = 12
--WEPS
Schema.InvMassTbl["fo3_revolver"] = 3
Schema.InvMassTbl["fo3_10mm"] = 3
Schema.InvMassTbl["fo3_10mm_carbine"] = 6
Schema.InvMassTbl["fo3_10mm_sub"] = 6
Schema.InvMassTbl["fo3_m_9iron"] = 2
Schema.InvMassTbl["fo3_9mm"] = 3
Schema.InvMassTbl["fo3_9mm_sub"] = 4
Schema.InvMassTbl["fo3_ak112"] = 10
Schema.InvMassTbl["fo3_blaster"] = 4
Schema.InvMassTbl["fo3_m_bat"] = 2
Schema.InvMassTbl["fo3_m_baton"] = 2
Schema.InvMassTbl["fo3_mine_bot"] = 0.5
Schema.InvMassTbl["fo3_m_bumper"] = 12
Schema.InvMassTbl["fo3_chinesear"] = 8
Schema.InvMassTbl["fo3_combatsg"] = 7
Schema.InvMassTbl["fo3_crepeater"] = 6
Schema.InvMassTbl["fo3_doublebar"] = 8
Schema.InvMassTbl["fo3_fatman"] = 20
Schema.InvMassTbl["fo3_g_frag"] = 0.5
Schema.InvMassTbl["fo3_mine_base"] = 0.5
Schema.InvMassTbl["fo3_gattling"] = 16
Schema.InvMassTbl["fo3_hunting"] = 7
Schema.InvMassTbl["fo3_m_knife"] = 1
Schema.InvMassTbl["fo3_laserpistol"] = 3
Schema.InvMassTbl["fo3_laserrifle"] = 8
Schema.InvMassTbl["fo3_m_machete"] = 4
Schema.InvMassTbl["fo3_mauser"] = 3
Schema.InvMassTbl["fo3_multiplas"] = 11
Schema.InvMassTbl["fo3_m_golf"] = 1
Schema.InvMassTbl["fo3_m_pick"] = 3
Schema.InvMassTbl["fo3_plasmapistol"] = 3
Schema.InvMassTbl["fo3_plasmarifle"] = 9
Schema.InvMassTbl["fo3_sawnoff"] = 3
Schema.InvMassTbl["fo3_service"] = 7
Schema.InvMassTbl["fo3_m_shish"] = 3
Schema.InvMassTbl["fo3_10mm_sil"] = 3.5
Schema.InvMassTbl["fo3_sniper"] = 12
Schema.InvMassTbl["fo3_m_sledge"] = 14
Schema.InvMassTbl["fo3_teslacannon"] = 20
Schema.InvMassTbl["fo3_plasmaturbo"] = 10
--AID
Schema.InvMassTbl["Stimpack"] = 0.5
Schema.InvMassTbl["Buffout"] = 0.5
Schema.InvMassTbl["Doctors Bag"] = 1
Schema.InvMassTbl["Healing Powder"] = 1
Schema.InvMassTbl["Jet"] = 0.5
Schema.InvMassTbl["MedX"] = 0.5
Schema.InvMassTbl["Psycho"] = 0.5
Schema.InvMassTbl["Stealth Boy"] = 1
Schema.InvMassTbl["Super Stimpack"] = 1
Schema.InvMassTbl["Ant Meat"] = 1
Schema.InvMassTbl["Atomic Cocktail"] = 1
Schema.InvMassTbl["Cram"] = 1
Schema.InvMassTbl["Iguana Bits"] = 1
Schema.InvMassTbl["Iguana Stew"] = 1
Schema.InvMassTbl["Iguana on a Stick"] = 1
Schema.InvMassTbl["InstaMash"] = 1
Schema.InvMassTbl["Molerat Steak"] = 1
Schema.InvMassTbl["Molerat Meat"] = 1
Schema.InvMassTbl["Nuka Cola"] = 1
Schema.InvMassTbl["Pork N Beans"] = 1
Schema.InvMassTbl["Strange Meat"] = 1
Schema.InvMassTbl["Strange Stew"] = 1
--MISC
Schema.InvMassTbl["10mm Casing"] = 1
Schema.InvMassTbl["Belt"] = 0.5
Schema.InvMassTbl["Bloodpack"] = 0.5
Schema.InvMassTbl["Brahmin Dung"] = 0.5
Schema.InvMassTbl["Cherry Bomb"] = 0.5
Schema.InvMassTbl["Deathclaw Egg"] = 2
Schema.InvMassTbl["Deathclaw Hand"] = 1
Schema.InvMassTbl["E-Cell Casing"] = 1
Schema.InvMassTbl["Gecko Hide"] = 1
Schema.InvMassTbl["Glass"] = 1
Schema.InvMassTbl["Holo Disk"] = 1
Schema.InvMassTbl["Lead"] = 0.5
Schema.InvMassTbl["Leather"] = 1
Schema.InvMassTbl["Liquid Coolant"] = 1
Schema.InvMassTbl["Lunchbox"] = 1
Schema.InvMassTbl["Scope"] = 0.5
Schema.InvMassTbl["Scrap Electronics"] = 0.5
Schema.InvMassTbl["Sensor Module"] = 1
Schema.InvMassTbl["Soda Bottle"] = 0.5
Schema.InvMassTbl["Steam Gauge"] = 1
Schema.InvMassTbl["Surgical Tubing"] = 1
Schema.InvMassTbl["Syringe"] = 1
Schema.InvMassTbl["Turpentine"] = 1

--NAME OF ITEMS
Schema.InvNameTbl["holodisk"] = "Holo Disk"
Schema.InvNameTbl["scrapmetal"] = "Scrap Metal"
Schema.InvNameTbl["metalfrag"] = "Metal Fragments"
Schema.InvNameTbl["cont_key"] = "Key"
Schema.InvNameTbl["gamb_chip"] = "Casino Chips"
Schema.InvNameTbl["casing_10mm"] = "10mm Casing"
Schema.InvNameTbl["casing_ecell"] = "E-Cell Casing"
Schema.InvNameTbl["belt"] = "Belt"
Schema.InvNameTbl["deathclaw_egg"] = "Deathclaw Egg"
Schema.InvNameTbl["bloodpack"] = "Bloodpack"
Schema.InvNameTbl["brahmin_dung"] = "Brahmin Dung"
Schema.InvNameTbl["cherrybomb"] = "Cherry Bomb"
Schema.InvNameTbl["deathclaw_hand"] = "Deathclaw Hand"
Schema.InvNameTbl["geckohide"] = "Gecko Hide"
Schema.InvNameTbl["glass"] = "Glass"
Schema.InvNameTbl["lead"] = "Lead"
Schema.InvNameTbl["leather"] = "Leather"
Schema.InvNameTbl["liquid_coolant"] = "Liquid Coolant"
Schema.InvNameTbl["lunchbox"] = "Lunchbox"
Schema.InvNameTbl["scope"] = "Scope"
Schema.InvNameTbl["scrapelec"] = "Scrap Electronics"
Schema.InvNameTbl["scrapmetal"] = "Scrap Metal"
Schema.InvNameTbl["sensormodule"] = "Sensor Module"
Schema.InvNameTbl["sodabottle"] = "Soda Bottle"
Schema.InvNameTbl["steamgauge"] = "Steam Gauge"
Schema.InvNameTbl["surgicaltubing"] = "Surgical Tubing"
Schema.InvNameTbl["syringe"] = "Syringe"
Schema.InvNameTbl["turpentine"] = "Turpentine"
--AID
Schema.InvNameTbl["fo3_aid_stimpack"] = "Stimpack"
Schema.InvNameTbl["fo3_aid_superstim"] = "Super Stimpack"
Schema.InvNameTbl["fo3_aid_stealth"] = "Stealth Boy"
Schema.InvNameTbl["fo3_aid_docbag"] = "Doctors Bag"
Schema.InvNameTbl["fo3_aid_buffout"] = "Buffout"
Schema.InvNameTbl["fo3_aid_healingp"] = "Healing Powder"
Schema.InvNameTbl["fo3_aid_jet"] = "Jet"
Schema.InvNameTbl["fo3_aid_medx"] = "MedX"
Schema.InvNameTbl["fo3_aid_mentats"] = "Mentats"
Schema.InvNameTbl["fo3_aid_psycho"] = "Psycho"
Schema.InvNameTbl["fo3_aid_antmeat"] = "Ant Meat"
Schema.InvNameTbl["fo3_aid_atomic"] = "Atomic Cocktail"
Schema.InvNameTbl["fo3_aid_cram"] = "Cram"
Schema.InvNameTbl["fo3_aid_igbits"] = "Iguana Bits"
Schema.InvNameTbl["fo3_aid_iguana"] = "Iguana on a Stick"
Schema.InvNameTbl["fo3_aid_igstew"] = "Iguana Stew"
Schema.InvNameTbl["fo3_aid_instamash"] = "InstaMash"
Schema.InvNameTbl["fo3_aid_molemeat"] = "Molerat Meat"
Schema.InvNameTbl["fo3_aid_steak"] = "Molerat Steak"
Schema.InvNameTbl["fo3_aid_nuka"] = "Nuka Cola"
Schema.InvNameTbl["fo3_aid_porknbeans"] = "Pork N Beans"
Schema.InvNameTbl["fo3_aid_humanmeat"] = "Strange Meat"
Schema.InvNameTbl["fo3_aid_strangestew"] = "Strange Stew"
--AMMO
Schema.InvNameTbl["fo3_ammo_308"] = ".308 Rounds"
Schema.InvNameTbl["fo3_ammo_44"] = ".44 Magnum Rounds"
Schema.InvNameTbl["fo3_ammo_10mm"] = "10mm Rounds"
Schema.InvNameTbl["fo3_ammo_12g"] = "12 Gauge Rounds"
Schema.InvNameTbl["fo3_ammo_556mm"] = "5.56mm Rounds"
Schema.InvNameTbl["fo3_ammo_9mm"] = "9mm Rounds"
Schema.InvNameTbl["fo3_ammo_apcell"] = "Alien Power Cell"
Schema.InvNameTbl["fo3_ammo_ecpack"] = "EC-Pack"
Schema.InvNameTbl["fo3_ammo_ecell"] = "Energy-Cell"
Schema.InvNameTbl["fo3_ammo_mfcell"] = "Microfusion Cell"
Schema.InvNameTbl["fo3_ammo_5mm"] = "5mm Rounds"
Schema.InvNameTbl["fo3_ammo_nuke"] = "Mini-Nuke"
--WEPS
Schema.InvNameTbl["fo3_10mm"] = "10mm Pistol"
Schema.InvNameTbl["fo3_10mm_sub"] = "10mm Sub-Machine Gun"
Schema.InvNameTbl["fo3_10mm_carbine"] = "10mm Carbine"
Schema.InvNameTbl["fo3_m_9iron"] = "9 Iron"
Schema.InvNameTbl["fo3_9mm"] = "9mm Pistol"
Schema.InvNameTbl["fo3_9mm_sub"] = "9mm Sub-Machine Gun"
Schema.InvNameTbl["fo3_ak112"] = "AK-112"
Schema.InvNameTbl["fo3_m_baton"] = "Police Baton"
Schema.InvNameTbl["fo3_mine_bot"] = "Bottlecap Mine"
Schema.InvNameTbl["fo3_m_bumper"] = "Bumper Sword"
Schema.InvNameTbl["fo3_crepeater"] = "Cowboy Repeater"
Schema.InvNameTbl["fo3_doublebar"] = "Double Barreled Shotgun"
Schema.InvNameTbl["fo3_g_frag"] = "Frag Grenade"
Schema.InvNameTbl["fo3_hunting"] = "Hunting Rifle"
Schema.InvNameTbl["fo3_m_knife"] = "Kicthen Knife"
Schema.InvNameTbl["fo3_laserpistol"] = "Laser Pistol"
Schema.InvNameTbl["fo3_m_machete"] = "Machete"
Schema.InvNameTbl["fo3_mauser"] = "Chinese Pistol"
Schema.InvNameTbl["fo3_multiplas"] = "Multiplas Rifle"
Schema.InvNameTbl["fo3_m_golf"] = "Nephi's Golf Driver"
Schema.InvNameTbl["fo3_m_pick"] = "Pickaxe"
Schema.InvNameTbl["fo3_plasmapistol"] = "Plasma Pistol"
Schema.InvNameTbl["fo3_sawnoff"] = "Sawn-off Shotgun"
Schema.InvNameTbl["fo3_service"] = "Service Rifle"
Schema.InvNameTbl["fo3_m_shish"] = "Shishkebab"
Schema.InvNameTbl["fo3_10mm_sil"] = "Silenced 10mm Pistol"
Schema.InvNameTbl["fo3_sniper"] = "Sniper Rifle"
Schema.InvNameTbl["fo3_m_sledge"] = "Super Sledge Hammer"
Schema.InvNameTbl["fo3_teslacannon"] = "Tesla-Beaton Prototype"
Schema.InvNameTbl["fo3_plasmaturbo"] = "Turbo Plasma Rifle"
Schema.InvNameTbl["fo3_chinesear"] = "Chinese Assault Rifle"
Schema.InvNameTbl["fo3_revolver"] = ".44 Magnum Revolver"
Schema.InvNameTbl["fo3_blaster"] = "Alien Blaster"
Schema.InvNameTbl["fo3_combatsg"] = "Combat Shotgun"
Schema.InvNameTbl["fo3_mine_base"] = "Frag Mine"
Schema.InvNameTbl["fo3_gattling"] = "Gatling Laser"
Schema.InvNameTbl["fo3_laserrifle"] = "Laser Rifle"
Schema.InvNameTbl["fo3_maria"] = "Maria"
Schema.InvNameTbl["fo3_plasmarifle"] = "Plasma Rifle"
Schema.InvNameTbl["fo3_pipboy3000"] = "PipBoy 3000"
Schema.InvNameTbl["fo3_pda"] = "PipBoy 2500"
Schema.InvNameTbl["fo3_m_bat"] = "Baseball Bat"
Schema.InvNameTbl["fo3_m_base"] = "Fists"
Schema.InvNameTbl["fo3_fatman"] = "Fatman"

