
--------------------------
--LANIUS
local lan_dir = "unique_chars/lanius"
RegisterChatTalk("A tribe called the Great Khans",lan_dir.."/a_tribe_called_khans.mp3","Legate Lanius")
RegisterChatTalk("Another kill",lan_dir.."/another_kill.mp3","Legate Lanius")
RegisterChatTalk("Battle is already won",lan_dir.."/battle_won.mp3","Legate Lanius")
RegisterChatTalk("Better equiped to take objectives",lan_dir.."/better_to_take.mp3","Legate Lanius")
RegisterChatTalk("You are brave to face me, when all of NCR would not",lan_dir.."/brave_to_face_me.mp3","Legate Lanius")
RegisterChatTalk("Caesar has been seen walking among the troops",lan_dir.."/caesar_seen.mp3","Legate Lanius")
RegisterChatTalk("Caesars will is made true through me",lan_dir.."/caesars_will.mp3","Legate Lanius")
RegisterChatTalk("You cant hide from me",lan_dir.."/cant_hide.mp3","Legate Lanius")
RegisterChatTalk("Vegas, you cannot truly be of that city of cowards",lan_dir.."/city_of_cowards.mp3","Legate Lanius")
RegisterChatTalk("Coward",lan_dir.."/coward.mp3","Legate Lanius")
RegisterChatTalk("will not save you",lan_dir.."/coward_2.mp3","Legate Lanius")
RegisterChatTalk("Death to profligates",lan_dir.."/death_to_p.mp3","Legate Lanius")
RegisterChatTalk("Die profligate",lan_dir.."/die_p.mp3","Legate Lanius")
RegisterChatTalk("Dont bear the mark of the bear",lan_dir.."/dont_bear_mark.mp3","Legate Lanius")
RegisterChatTalk("Dont belong here",lan_dir.."/dont_belong_here.mp3","Legate Lanius")
RegisterChatTalk("Know nothing of who I am",lan_dir.."/dont_know_me.mp3","Legate Lanius")
RegisterChatTalk("Waste my time",lan_dir.."/dont_waste_my_time.mp3","Legate Lanius")
RegisterChatTalk("Let our strengths settle this",lan_dir.."/enough_words.mp3","Legate Lanius")
RegisterChatTalk("Enough",lan_dir.."/enough.mp3","Legate Lanius")
RegisterChatTalk("I shall face you alone",lan_dir.."/face_you_alone.mp3","Legate Lanius")
RegisterChatTalk("Fair kill",lan_dir.."/fair_kill.mp3","Legate Lanius")
RegisterChatTalk("I see you fight with words",lan_dir.."/fight_with_words.mp3","Legate Lanius")
RegisterChatTalk("Those are your final words?",lan_dir.."/final_words.mp3","Legate Lanius")
RegisterChatTalk("Fool",lan_dir.."/fool.mp3","Legate Lanius")
RegisterChatTalk("For Caesar",lan_dir.."/for_caesar.mp3","Legate Lanius")
RegisterChatTalk("For the Legion",lan_dir.."/for_the_legion.mp3","Legate Lanius")
RegisterChatTalk("With their commander dead the NCR will pull out",lan_dir.."/general_dead.mp3","Legate Lanius")
RegisterChatTalk("General Oliver",lan_dir.."/general_oliver.mp3","Legate Lanius")
RegisterChatTalk("I am the commander of this army",lan_dir.."/i_am_lanius.mp3","Legate Lanius")
-----------------